version: 2
updates:
  - package-ecosystem: "vcpkg"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
    labels:
      - "dependencies"
      - "vcpkg"
    commit-message:
      prefix: "deps"
